### ISSUE TITLE
Can I use oath api calls with pyresttest

### ISSUE THREAD

**Issue by joykrogers** [svanoort/pyresttest#105]
I saw you had an example of basic authentication in the doc.  Do you know if pyresttest support oath authorization?  If so, do you have an example.  

I really enjoy your pyresttest tool.

**Comment by svanoort** [comment]
Thank you, I'm glad you've found it helpful!  Yes, you can do OAuth with PyrestTest, it provides all the necessary components. 

The specific code will depend on how your API token is obtained and used, since each provider is a bit different.  But in general, you'll do the following:

1. Call the authorization API, passing authentication information (basic auth, request body, or headers). 2. For the authorization call above, define an extractor to retrieve the API token and information and store it to a variable for later use in requests.
2. Use the authorization token in calls, with templated headers to insert it using the variable (or templated URL using it as a query parameter, or templating of a request body if it is supplied there).

Something like this is easy to convert from curl calls to PyCurl:
https://gist.github.com/caspyin/2288960

The only catch to remember is that some APIs will need URL encoded inputs, which PyRestTest doesn't have an automatic filter for (no converter functions to do automatic encoding/decoding, since there hasn't been a call for them yet, so that has to be done manually or by custom extensions). 

Does that help answer your question?  If you've got a particular documented API, I can provide some tips about how to do this most effectively with PyRestTest

**Comment by joykrogers** [comment]
Thanks so much for the info.  It is very helpful and does answer my question.  I will research the link your provided and do some more debugging with my api call.  I haven't used oauth before so I'm sure it is just a syntax error I have somewhere in the request.

**Comment by svanoort** [comment]
I'm glad that was of some assistance!   Two tips that may be of help: 

* Turn on verbose mode when running PyRestTest (logging level debug + --verbose argument).  Often that will reveal more information about what is going wrong.  
* If you're still not sure what is going wrong, try doing the same calls in curl with verbose mode and comparing to the above.  PyRestTest is tightly tied to PyCurl, so the two behave similarly. If curl works but PyRestTest doesn't, the problem is usually a missing header that needs to be explicitly set, or the request body isn't correctly formatted. 

Since it sounds like your question is answered, I'm going to close out the issue, if that's okay. But please feel free to add additional comments in here or open a new one if you hit sticking points with the OAuth call!
