### ISSUE TITLE
python-pycurl installed but still get the not installed error on CentOS 6

### ISSUE THREAD

**Issue by Leo-G** [svanoort/pyresttest#113]
Package python-pycurl-7.19.0-8.el6.x86_64 already installed and latest version

I am using python 3.4 not sure what the issue is

**Comment by Leo-G** [comment]
I solved this by installing

      yum install libcurl-devel

On CentOS

     sudo apt-get install libcurl4-openssl-dev

On Ubuntu, Can this be added to the docs?

**Comment by svanoort** [comment]
Hi, thanks speaking up!   I'm a little confused about the environment here.  Please could you clarify what method was used to install PyRestTest (pip, git clone, or git clone + setup.py), and is there is a python 2.x install present as well as python 3.4?   CentOS 6 comes with python 2.6 natively (although you could use an RPM from other sources to install a later python), and that's what I've used in installation testing.

PyRestTest does not have python 3 support yet: I put a lot of work towards this in the last release, but I am still working through remaining compatibility issues to get it into the next release (currently slated for December).  I'll have to include testing for this in that effort -- I've seen similar issues already, and the root cause was packages available for python 2 but not python 3 (fixable by using 'pip3 install' instead of 'pip install'.

**Comment by Leo-G** [comment]
I used pip to install pyRESTtest, I created a virtualenv and installed python 3.4 for there, I don't think the problem is pip3 as I tried this ubuntu as well and got the same error, The same is mentioned at http://stackoverflow.com/questions/23937933/could-not-run-curl-config-errno-2-no-such-file-or-directory-when-installing , also I would apreciate if you can tell me how to solve this though https://github.com/svanoort/pyresttest/issues/114, I am not sure if that is related to python 3

**Comment by svanoort** [comment]
Ah, yes, that one.  This is linked to known issues, unfortunately, in packages I don't maintain.  If that solution offers a fix, it's worth including in docs for use with virtualenvs (after some testing).  

Under this main doc:  https://github.com/svanoort/pyresttest#how-do-i-get-it you'll see I mention installing pycurl via the native packages and not pip, because it doesn't handle libcurl right on CentOS. 

Separately there's a mention of avoiding combining pycurl with virtualenvs in that same doc... because you guessed it, the native libraries.   

I opted for Docker images to avoid some of these egregious pain points when testing different environments because it was so very painful: https://github.com/svanoort/pyresttest/tree/master/docker

Native libraries interfacing with python can be such a gigantic pain in the butt sometimes, I swear.

**Comment by svanoort** [comment]
@Leo-G This has been added to documentation with this commit:  https://github.com/svanoort/pyresttest/commit/b79d7d896cb20f165dd5cda63e05c1d0afcea0fc

I swear, if it weren't for benchmarking and some of the powerful custom options I'd drop PyCurl for requests, because the native libraries cause so many installation headaches.
