### ISSUE TITLE
ImportError: No module named 'past'

### ISSUE THREAD

**Issue by Leo-G** [svanoort/pyresttest#114]
Stack trace

resttest.py http://localhost:5000 test.yaml
Traceback (most recent call last):
  File "/sites/Flask-Scaffold/venv-3.4/bin/resttest.py", line 3, in <module>
    from pyresttest import resttest
  File "/sites/Flask-Scaffold/venv-3.4/lib/python3.4/site-packages/pyresttest/resttest.py", line 25, in <module>
    from past.builtins import basestring
ImportError: No module named 'past'

**Comment by svanoort** [comment]
PyRestTest does not have Python 3 support yet, [please use python 2.6 or 2.7 for now.](https://github.com/svanoort/pyresttest#system-requirements).  If you're in an all-python3 environment, there's a neowinx/pyresttest Docker image that someone else put together, which may make this easier.

I am working very actively towards python 3 support for the 1.7.0 release, it's one of the key elements of [that milestone](https://github.com/svanoort/pyresttest/milestones/1.7.0%20-%20Python%203%20+%20Parsing/Configuration%20Internals).    Getting to a state where unit tests pass is tracked in an existing issue: https://github.com/svanoort/pyresttest/issues/98 

The last release included a lot of changes intended to build toward python 3 support but also added a dependency on the 'future' library that provides the past module.  I'm going to go ahead and close this issue because it's not a supported version yet, and I already have a fix + tests for this included in my working branch which will be merged for the next release.   For now, I'm not offering that branch up for public consumption (yet) because there are still some significant compatibility issues remaining.

**Comment by svanoort** [comment]
@Leo-G  I'll give the fix for this immediate issue here:

If you're using *all* python3 and don't have pip3 for that (otherwise use pip3)
```shell
pip install future
```

But if you actually try to use PyRestTest with python 3, you're going to find a whole raft of other :bug:s (which I'm working through)

**Comment by Leo-G** [comment]
@svanoort Thx,

I don't mind helping you out, I would really like to use your project for testing in my project https://github.com/Leo-G/Flask-Scaffold

**Comment by svanoort** [comment]
@Leo-G Oh, okay!  Well, yes, help would be very welcome!

I'm presently working off of branch feature-refactor-parsing: https://github.com/svanoort/pyresttest/tree/feature-refactor-parsing

Right now I'm trying to resolve the Unicode handling aspect -- this is pretty well documented here: https://github.com/svanoort/pyresttest/issues/104

If you'd like to pick up and start helping get those tests up & fixed, it would be extremely welcome!  (Submit PRs against that custom branch please.)

The reason this is a necessary precursor for full python 3 support is that nasty string --> bytes and unicode --> str changeover from python 2->3.   

One other note: I've pulled in the 'six' library to help with this.  It's a single file, so for distribution we need to pull it into the pyresttest folder and adjust the imports to that path.

Thanks!

**Comment by Leo-G** [comment]
ok, will take a look at them when I have time, here is another error after I installed future

Traceback (most recent call last):
  File "/sites/Flask-Scaffold/venv-3.4/bin/pyresttest", line 3, in <module>
    from pyresttest import resttest
  File "/sites/Flask-Scaffold/venv-3.4/lib/python3.4/site-packages/pyresttest/resttest.py", line 29, in <module>
    from binding import Context
ImportError: No module named 'binding'

**Comment by svanoort** [comment]
This is a probably linked to the virtualenv somehow, since it can't load one of the core libraries and that works in normal python 3 testing.   For now, please use the docker images here for now, there's one I built out specifically for python 3:  https://github.com/svanoort/pyresttest/blob/master/building.md

There's a reason I don't recommend (or provide support) for using virtualenvs with pyresttest at the moment.  Maybe in the future, but right now it's yet another set of environments that require debugging and layering that on top of python 3 will just make life difficult.

**Comment by svanoort** [comment]
@Leo-G  Of course, that's just my advice. If you want to use virtualenvs, you are of course very welcome to investigate why they misbehave and submit a PR with fixes and docs, which would be amazing!
