### ISSUE TITLE
Set default headers for test set

### ISSUE THREAD

**Issue by jcelliott** [svanoort/pyresttest#116]
Is there a way to set default headers for a test set. For example, if I'm testing a json rest api I want to send `Content-Type: application/json` with every request. It would be nice to just specify that once in the `config` section. I didn't see it in the documentation, but I may have missed it.

**Comment by svanoort** [comment]
Hi @jcelliott !  You can use a variable and template for individual header values, if you like, but unfortunately there's not a way to define the entire set of headers at the config level for the whole testset yet.

The good news is that there's already a larger enhancement on the roadmap with v2.0 to add this (and much, much more): https://github.com/svanoort/pyresttest/issues/93 -- the next release includes a major chunk of work intended to lay the groundwork.

The bad news is that it requires some significant refactoring before this is an option (and there is a risk of compatibility breaks), so it will be a while coming.

I hope that answers your question?  (For tidiness, this issue will be closed out, since the enhancement is tracked elsewhere, but if you have other questions around this, I'd be happy to answer them).
