### ISSUE TITLE
Dependency: pip install pyyaml

### ISSUE THREAD

**Issue by nitrocode** [svanoort/pyresttest#143]
Hi, just want to mention that you forgot to add a dependency.

For some reason, I wasn't able to use pip to install pyyaml on Windows 8 but I could using the pyyaml exe's.

**Comment by svanoort** [comment]
@nitrocode  Windows isn't a supported platform, because of issues with installing packages including native code (pycurl and pyyaml).   I also do not have access to a system with a current version of Windows to test against. 

However, the pyyaml dependency is mentioned here: https://github.com/svanoort/pyresttest#what-is-it

I am going ahead and closing this issue, because it's an unsupported configuration, and because the issue here is really pyyaml and not PyRestTest.

**Comment by nitrocode** [comment]
@svanoort right. I just meant that it should be included in the documentation as an additional dependency. Before cloning the repository and running ./resttest.py, pycurl and pyyaml need to be installed. The current readme.md does not mention pyyaml as a required dependency.

**Comment by svanoort** [comment]
@nitrocode Ah, couldn't hurt -  I added a mention. https://github.com/svanoort/pyresttest/commit/31c3f76a9976c431e4b2d3053cf9995e0836d161

I really strongly encourage you to use docker containers if you're going to run on windows though (running via docker machine).  Someone else threw together a basic image:  https://github.com/neowinx/pyresttest

At some point I'd like to add CI builds so people can use the in-progress, unreleased version as a docker image too.
