### ISSUE TITLE
Unable to send body with a DELETE request

### ISSUE THREAD

**Issue by spradeepv** [svanoort/pyresttest#162]
Consider the following template which is used to delete an entity from DB.

    - test:
        - group: "Basic Test"
        - name: "Delete 10.24.39.202"
        - url: "/v1/switch"
        - method: 'DELETE'
        - expected_status: [200]
        - body: '{"ip_address": "10.24.39.202"}'
        - headers: {'Authorization': 'Basic ZGV2ZWw6WjNGSmVFTlliMUJvYlVSclVrOWhXRVp3ZDIwNFUzQktSekpzTjBnMGVYVT0=',
                    'Content-Type': 'application/json'}

This doesn't work and I get the following error while decoding the body:

      Traceback (most recent call last):
      File "/home/stack/git/server/switch.py", line 1880, in delete
        request = json.loads(self.request.body)
      File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded

From the changelogs, pyresttest supports body in delete request

    1.6.0 Mon Oct 12 07:30:00 2015 -0400
    BETA: support setting request body on all request types, if present
    Allows (for example) DELETE methods that set a request body
    Caveat: does not set length if 0

**Comment by svanoort** [comment]
@spradeepv Hmm, it may be that the DELETE method in this case requires an explicit body size to be set.  Do you have any ideas for how to consistently test this?   

I've created a PR that *might* fix this, but don't have a good example to test it (since few APIs will accept a DELETE request with a body).  The PR is https://github.com/svanoort/pyresttest/pull/164 -- you're welcome to give it a shot and report back if it works.

**Comment by spradeepv** [comment]
@svanoort I tried the fix, but I still face the same issue.

**Comment by spradeepv** [comment]
@svanoort The following code fixed the issue:

```
elif self.method == u'DELETE':
            curl.setopt(curl.CUSTOMREQUEST, 'DELETE')
            if bod is not None:
                curl.setopt(pycurl.POSTFIELDS, bod)
                curl.setopt(pycurl.POSTFIELDSIZE, len(bod))
```

**Comment by svanoort** [comment]
@spradeepv Thank you for your contribution and for testing this out.  This is a great example of the challenges working with the LibCurl APIs (in this case, there's no way to tell whether the custom request should use POST semantics or PUT semantics).

**Comment by spradeepv** [comment]
I had been stuck for almost 3 days with this issue, until I decided to file a bug. Yes it is challenging working with these APIs. Anyways happy to have contributed to pyresttest. It is a great REST API testing framework. Hope to contribute more to this repository!!

**Comment by svanoort** [comment]
@spradeepv You're very welcome, and so was your contribution here (and for the other user's question).  I'm glad you're finding PyRestTest helpful (and keep an eye out, there are some [major enhancements](https://github.com/svanoort/pyresttest/issues/163) planned in the upcoming [1.8 milestone](https://github.com/svanoort/pyresttest/milestones/1.8.0%20Parsing+Scoping%20Enhancements) (some will probably move to 1.9, depending on what obstacles come up as well).

**Comment by spradeepv** [comment]
svanoort <https://github.com/svanoort> I have some questions regarding
using pyresttest with jenkins.

   - I know we can capture logs, but can we redirect logs to a specific
   file format (like .htm/.xhtml)
   - I had looked into https://github.com/svanoort/pyresttest/issues/43 When
   can we expect this to be completed? I am willing to contribute too, if you
   need help.
   - Is there a way to disable a test? If not, can we introduce one?

Regards,
Pradeep. S

**Comment by svanoort** [comment]
@spradeepv ,

> I know we can capture logs, but can we redirect logs to a specific
   file format (like .htm/.xhtml)

No, this would be the same thing as the xUnit output (or an extension of it).

> When can we expect this to be completed?

This is a deceptively large/complex feature, and it is tentatively planned for the next release (v1.8.0). It might hit the master branch sooner, in a rough state. You can see the current list of fixes & enhancements planned for this release [in the milestone](https://github.com/svanoort/pyresttest/milestones/1.8.0%20Parsing+Scoping%20Enhancements). 

Currently, xUnit output and improved variable (https://github.com/svanoort/pyresttest/issues/101) use are tied for most-requested features.   Both are very large features and require rewriting some of the framework internals, so it's likely that only one will make it into the release unless I get a lot of community help on smaller items.  xUnit has actually been bumped up to finish sooner, because I found a way to implement it without requiring as much effort.

> I am willing to contribute too, if you need help.

Absolutely!  The best way to help with this to help free up time I'm spending answering questions/issues, writing documentation, and implementing small features so that I can focus on the bigger tasks.  In particular, [any issue marked "help wanted'](https://github.com/svanoort/pyresttest/labels/help%20wanted) is something I'd welcome a community PR for.  In particular, https://github.com/svanoort/pyresttest/issues/100 really needs some work and would be easy for somebody to take on; this would reduce the number of questions tremendously if done right.

The xUnit feature itself depends on a moderately complex refactoring of the test execution logic (moving it into the test/benchmark classes and using callbacks to do logging).  See https://github.com/svanoort/pyresttest/issues/163 item A1 for details of that.  As it stands, I expect some issues with the inter-module dependencies (and testing), but just finished the 1.7.x release last weekend and haven't had time to dig further yet.

> Is there a way to disable a test? If not, can we introduce one?

Well, you can always comment out the appropriate sections of the YAML.  It's something to consider down the road, but would probably have to be part of the 1.9.0 or [2.0.0 milestone](https://github.com/svanoort/pyresttest/milestones/2.0%20-%20Major%20internal%20refactoring%20for%20extensibility)  because to do it in a useful way (reporting skipped tests, not just pass/fail) would make more sense once the logging and config parsing allow it (1.8/1.9).

By the way, if you'd like to discuss overall project plans, I'd like to ask that this be done in either the Gitter channel (link on the main README) or in the issues for the features in question (it's hard to track discussions in closed issues). 

Regards,
Sam
