### ISSUE TITLE
Using pyresttest as library and trying to execute two or more yaml files in parallel, causes issues.

### ISSUE THREAD

**Issue by akshay059** [svanoort/pyresttest#183]
Using pyresttest as library and trying to execute two or more yaml files in parallel, causes issues.

steps:
try to run multiple yaml files in parallel.

result:
test runs interfere with each other and cause test runs to fail.

**Comment by spradeepv** [comment]
@akshay059, could you explain more on how you ran the tests? Are the
tests(response) independent of each other?

**Comment by akshay059** [comment]
I invoked it from a view in a django project, there were two yaml files that ran in parallel which caused the issue. Tests in those files were independent of each other.

**Comment by spradeepv** [comment]
I think the requests are dependent on each other, can you elaborate on the
api's(is it DB changes)?

Regards,
Pradeep. S

**Comment by akshay059** [comment]
Both yaml files just do a lot of get requests with different params and validate the response using a  common json schema file.
When I put lock on the call to main, everything works correctly, although requests are processed one by one. So I am pretty sure it is a threading issue.

I moved all the code to a class file from the module, which worked when using completely independent test files, but again failed when executing yaml files which used same json schema files.

I think issue is where we are using cd but I am not sure.

**Comment by spradeepv** [comment]
@svanoort - I think we need your help here.

**Comment by svanoort** [comment]
@akshay059  I think you are correct - the os.chdir operation here changes the working directory completely, and is used in the cd operation.  I've made an attempt to correct this by adding a lock around just the pieces using it.  It's hacky (better to drop the CD utility already and make all paths absolute to the correct locations, I think), but it should resolve it.    

Please give this version of source a try and let me know if it works: https://github.com/svanoort/pyresttest/pull/186

Never thought I'd see threading issues in python code!  :smile: 

@spradeepv  As always, thank you for assisting with questions and investigating issues.  I am adding a mention to the changelog for this, because it contributes even more toward making big features/enhancements possible than writing code would.

**Comment by spradeepv** [comment]
@svanoort No issueses. Happy to help!!

**Comment by akshay059** [comment]
@svanoort Adding lock to cd worked :)
Thanks for the help :+1:
@spradeepv thanks :+1:
