### ISSUE TITLE
Reuse a value extracted from jsonpath_mini on a different test set

### ISSUE THREAD

**Issue by Sivascorner** [svanoort/pyresttest#38]
Thanks for this excellent test tool. I did see that, we could extract HTTP response and use them in validators. Is there a method to extract the value  and use in subsequent test set(use it as a variable). 

I tried jsonpath_mini with variable_binds but that did not work. Can you provide a example for that ?

--Thanks

**Comment by svanoort** [comment]
Hi,
This can be accomplished with an extract_bind: there is an example of this here:
https://github.com/svanoort/pyresttest/blob/master/miniapp-extract-validate.yaml

The extract bind will pull content from the response, and bind then to the named variable:
```yaml
- extract_binds:
        - 'id': {'jsonpath_mini': 'my.element.value'}
```
This will extract the jsonpath_mini element and bind it to the 'id' variable, following tests can use that variable.
Validators can use the same jsonpath_mini expression to validate what that content is (within the test).

I'm opening an [issue](https://github.com/svanoort/pyresttest/issues/39) to improve documentation on the variable binding / extraction / generators, because while it references this, it's not as helpful as it could be. 

Now, there's a catch here: each TestSet runs in a separate context, and variables are isolated to the context they were assigned in, so you can't use the results across tests, you have to add later tests with the variable to the same test.  

TestSets are isolated in this fashion so users can rely on them being usable as completely independent entities, and because the alternative introduces a lot of potential problems with little gain. 

Kind regards,
Sam

**Comment by Sivascorner** [comment]
Thanks you so much, It worked !!
