### ISSUE TITLE
It would be nice to be able to view the generated curl request of a given test.

### ISSUE THREAD

**Issue by jeanCarloMachado** [svanoort/pyresttest#40]
This would make easy for developers to debug the requests and tweak them to match the real needs of the tests. 
Maybe a paramenter like: ``--print-curl-request=true``

**Comment by svanoort** [comment]
HI, 
I think this should already be covered by a combination of these: 

--print-bodies=True
--log=DEBUG
--interactive=True

Interactive mode will print the request. 
Print-bodies will print the response body. 
Debug log level ensures you get the maximum about of debugging information. 

Let me know if you run into any issues with those!
Thanks,
Sam

**Comment by jeanCarloMachado** [comment]
I was really looking for a way to get the full curl request. In a way that I could simply copy it from pyresttest output and paste in a new tab, ready to use. Currently, with the available data, I need to mount the request if I want to test it.

**Comment by svanoort** [comment]
If I understand you correctly, you're looking to be able to be able to convert a pycurl call to a command line execution? 

That is a bit trickier than it sounds, because we're directly coupling with LibCurl via PyCurl (passing in callback functions for things like the request body).  I'm also not sure how broad the use case would be for this.

Let me offer an alternative that might facilitate your usecase (and others):
- Add option to enable pycurl verbose mode, which will log all information used in the request, so that a user can recreate it or debug it if needed. 

I have a hook for this already and have used it in debugging, but it's not exposed via user options. 

Would that facilitate your use cases?

**Comment by svanoort** [comment]
Closing this, since I *think* this is covered by the verbose option (to show all you need to generate a curl call).  Open to reopening if there is activity or demand for it, however.
