### ISSUE TITLE
WARNING:Failed to load jsonschema validator,

### ISSUE THREAD

**Issue by miqui** [svanoort/pyresttest#57]
WARNING:Failed to load jsonschema validator, make sure the jsonschema module is installed if you wish to use schema validators.
Test Group Default SUCCEEDED: 1/1 Tests Passed!

If i am not using json schema validation, how do i remove this warning?

**Comment by svanoort** [comment]
Fixed with commit https://github.com/svanoort/pyresttest/commit/4f4032c2d16a7ff7dfaa92bc8c76dc1883c8be6d

This is now a debug level log event, not a WARN level event.  By default it will be silent unless you set log level to debug. 

You will need to pull the latest code, though (this is not in a released state yet)

**Comment by svanoort** [comment]
@miqui It's released as of latest PIP release, by the way!
