### ISSUE TITLE
Reuse of previous GET response fields in subsequent GET requests in YAML

### ISSUE THREAD

**Issue by ksreddy543** [svanoort/pyresttest#62]
Hi,

Would like to reuse of first GET response fileds into next GET request REST url params.

For example:
==============
- test: # create entity
    - group: "Quickstart"
    - name: "Basic get"
    - url : "/v1/config/device"

Assume it returns list of devices with <Id, name > in response body as
 "device": [{ id : AUTO_GENRATED_ID1, name: abc} , {id:AUTOGENERATED_ID2 , name : xyz} ]. 

For the next test I like to GET info about ID: AUTOGENERATED_ID1 as REST URL request

 - url : "/v1/config/device/AUTOGENRATED_ID1"

How to write yaml to acheive it?

Also for dynamic REST URL params how can we define YAML?

ex: url/current_stock_price?Date:23062015

for the date param i want pass user defined date without modifying YAML file. Like in shell script
read argument or execute "date" command and pass it as argument to shell script. can we do similar to this in this framework?

Thanks in advance.

**Comment by svanoort** [comment]
**In order:**

1. For a fixed number of elements, you can use an extractor for each element, and then templating to do a fetch.  Please see the [content-test](https://github.com/svanoort/pyresttest/blob/master/pyresttest/content-test.yaml)  and the [advanced guide](https://github.com/svanoort/pyresttest/blob/master/advanced_guide.md)
2. If you want to pass in a user-defined date, you can pass in an environment variable and use the [environment variable generator](https://github.com/svanoort/pyresttest/blob/master/advanced_guide.md#generators-listing)  - if you'd like to do this in python (or with more logic around it), you can define a custom generator extension to do something fancier.

**Limitations on point 1:**
* There is no way to do a for-each loop within the tests at this time.  Benchmarks can loop over generator results, but they only do trivial testing.  This is by design, and would require redesigns to alter. 

I hope that answers both questions, please reply back if it does not, and I will be happy to reopen this issue. 

Kind regards, 
Sam
