### ISSUE TITLE
Issue with using variable extracted form header

### ISSUE THREAD

**Issue by scorchio** [svanoort/pyresttest#63]
Hello --

We've been trying to use pyresttest for testing a Spring web application, where for several operations a CSRF token needs to be used. pyresttest seems to be perfect for the task, but we couldn't get the header extraction work as it should for some reason...

    ---
    - config:
       - testset: "Example test set"

    - test:
       - name: "Initial call to get the CSRF"
       - url: "/get_token"
       - extract_binds:
         - token: { header: "x-csrf-token"}

    - test:
       - name: "Test call with token"
       - url: { template : "/example_endpoint/$token/" }

I'm testing with `pyresttest http://localhost:8081 test.yaml --interactive=true --log=debug` to see the calls and I see that it gives the following error message:

`ERROR:Test Failed: Test with token URL=http://localhost:8081/example_endpoint/$token/ Group=Default HTTP Status Code: 404`

...so the templating is surely off somewhere a bit.

Could someone please explain why this happens and how I could fix the above example to make it work? I would greatly appreciate any help.

Kind regards,
Zoltán

**Comment by svanoort** [comment]
Hi Zoltán,

Templating is a mature feature, but can hit issues if its input variable is not set correctly due to an extractor failure, and it appears extraction can fail silently in some cases (I've opened https://github.com/svanoort/pyresttest/issues/64 to fix this issue). 

Please, could you try setting the "--verbose" flag in addition to the "--log=debug" mode and capture the output from running the test again?  This will get the HTTP traffic back and forth. My thought is that something is subtly off in the header extraction (either the header name may be off, or headers may not be correct) or in the header processing (which is still a *relatively* new feature).

Kind regards,
Sam

**Comment by svanoort** [comment]
@scorchio  ^

**Comment by scorchio** [comment]
Uhm, I get `resttest.py: error: no such option: --verbose` when trying to do that. (We're using the pyresttest available in pip - version 1.3.1, I don't know whether we're missing something.)

**Comment by svanoort** [comment]
@scorchio Try updating: I've pushed all the latest out to PyPi so it should be available for install.

**Comment by svanoort** [comment]
With additional diagnostic info from a later issue, this has been found and fixed in: https://github.com/svanoort/pyresttest/commit/29ec38a888e4c647eeb2b33b363d3553a3646587
