### ISSUE TITLE
extracting json using extract_binds returns unicode string

### ISSUE THREAD

**Issue by night2tl** [svanoort/pyresttest#77]
when using something like this: 
    - extract_binds:
            - 'myJson': {'jsonpath_mini': 'json_field'}

Instead of returning an escaped answer like {\"access\":\"asdasd\"},
it returns a unicode one :  {u'access': u'asdasd'}

when referred to in other context as $myJson.

Which makes it incorrect for further usage in latter requests.

**Comment by svanoort** [comment]
Ah, I think I understand your confusion here.  The MiniJsonExtractor parses JSON before doing extraction, so if you're extracting a full data structure (a list or dictionary), it returns a python object, not a text string.  When used in a template, this may give unexpected results.

There's a couple solutions to this problem:

* **Simplest:** just extract simple fields (not full structures) and use them in a template like so:
https://github.com/svanoort/pyresttest/blob/master/pyresttest/content-test.yaml#L46

*A little clunkier I know, but usable.*

* **More powerful, but more complex:**  define a custom extractor (possible extending the JsonPathMini extractor) that converts the python object back to JSON strings.   See [extensions documentation](https://github.com/svanoort/pyresttest/blob/master/extensions.md).  It's perfectly safe to go in core if it doesn't add additional libraries, but does need unit testing. Would suggest extractor named jsonpath_mini_string.  **Another option would be a regex-based extractor (also valid, maybe more broadly useful).**  If you have the time, this would make a wonderful PR since it shouldn't be more than a couple hours work (otherwise I can add it as a future enhancement).

* **More powerful but harder option** define a custom extractor extension using [jsonpath-rw](https://github.com/kennknowles/python-jsonpath-rw) that offers even more power (on my radar as a future enhancement already).  This may be set to autoload on start if the library is installed, much like the [json schema validator](https://github.com/svanoort/pyresttest/blob/master/pyresttest/ext/validator_jsonschema.py). 

* **Superman mode:** add Jinja2 templating support as a optional extension (same mode as above). This one is a future goal after the next [major set of planned changes](https://github.com/svanoort/pyresttest/issues/46) unless I can find a clever and back-compatible way to insert it.  It will take a long time before it's an option though (read: probably months). 

Does that both answer your question and give some idea of where future options are going?

**Comment by svanoort** [comment]
@night2tl Your voice has been heard:  this is addressed explicitly in the next release by enhanced templating support in https://github.com/svanoort/pyresttest/issues/93  (scoped/dynamic templating... dynamic, in this case). 

Since I haven't heard any more feedback on this one, I'm going to go ahead and close it as a duplicate of the larger featureset.

**Comment by JohnnyWuMigme** [comment]
I tried creating a custom extractor named jsonpath_mini_string in validators.py. So you can just call 

`    - extract_binds:
        - 'sessionId': {'jsonpath_mini_string': 'sessionId'}`

and variable $sessionId refers later in template will be pure json string but not unicode.

Rename this attachment to validators.py and replace with original file in pyresttest install path.
(ie: my path: /Library/Python/2.7/site-packages/pyresttest-1.7.2.dev-py2.7.egg/pyresttest )

[validators.add_jsonpath_mini_string.py.txt](https://github.com/svanoort/pyresttest/files/1048842/validators.add_jsonpath_mini_string.py.txt)
